Automatic retrieval of run id for artifact download.

diff --git a/.github/workflows/infra-destroying.yaml b/.github/workflows/infra-destroying.yaml
--- a/.github/workflows/infra-destroying.yaml
+++ b/.github/workflows/infra-destroying.yaml
@@ -1,4 +1,4 @@
-name: Polybot Infrastructure Destroy Terraform
+name: Infrastructure Terraform Destroy
 
 on:
   workflow_dispatch:
@@ -21,13 +21,56 @@ on:
           - 'dev'
 
 jobs:
+  GetRunId:
+    runs-on: ubuntu-latest
+    outputs:
+      run_id: ${{ steps.set_run_id.outputs.run_id }}
+    steps:
+      - name: Check and Install curl
+        run: |
+          if ! command -v curl &> /dev/null
+          then
+            echo "curl could not be found. Installing curl..."
+            sudo apt-get update
+            sudo apt-get install -y curl
+          else
+            echo "curl is already installed."
+          fi
+
+      - name: Check and Install jq
+        run: |
+          if ! command -v jq &> /dev/null
+          then
+            echo "jq could not be found. Installing jq..."
+            sudo apt-get update
+            sudo apt-get install -y jq
+          else
+            echo "jq is already installed."
+          fi
+
+      - name: Fetch the latest successful workflow run ID from the Infra Deployment
+        id: set_run_id
+        run: |
+          LATEST_SUCCESS=$(curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
+            -H "Accept: application/vnd.github.v3+json" \
+            "https://api.github.com/repos/talorlik/INTPolybotServiceAWS/actions/workflows/infra-provisioning-main.yaml/runs?status=success&per_page=1" \
+            | jq -r '.workflow_runs[0].id')
+
+          echo "run_id=$LATEST_SUCCESS" >> $GITHUB_OUTPUT
+
+          echo "The latest successful run ID is $LATEST_SUCCESS"
+
   SetGlobals:
     runs-on: ubuntu-latest
+    needs:
+      - GetRunId
     strategy:
       matrix:
         region:
           - us-east-1
           - us-east-2
+    env:
+      ARTIFACT_NAME: ${{ github.event.inputs[ matrix.region ] }}-${{ inputs.environment }}-tf-outputs.json
     outputs:
       country: ${{ steps.set_values.outputs.country }}
       state: ${{ steps.set_values.outputs.state }}
@@ -47,19 +90,22 @@ jobs:
           fi
 
       - name: Download Output JSON file
-        uses: actions/download-artifact@v2
+        uses: actions/download-artifact@v4
         with:
-          name: ${{ github.event.inputs[ matrix.region ] }}/${{ inputs.environment }}/tf-outputs.json
+          name: ${{ env.ARTIFACT_NAME }}
+          github-token: ${{ secrets.GH_TOKEN }}
+          repository: talorlik/INTPolybotServiceAWS
+          run-id: ${{ needs.GetRunId.outputs.run_id }}
           path: ${{ github.workspace }}
 
       - name: Extract outputs from file and set as environment variables
         id: set_values
         run: |
-          echo "country=$(jq -r '.country' tf-outputs.json)" >> $GITHUB_OUTPUT
-          echo "state=$(jq -r '.state' tf-outputs.json)" >> $GITHUB_OUTPUT
-          echo "locality=$(jq -r '.locality' tf-outputs.json)" >> $GITHUB_OUTPUT
-          echo "organization=$(jq -r '.organization' tf-outputs.json)" >> $GITHUB_OUTPUT
-          echo "common_name=$(jq -r '.common_name' tf-outputs.json)" >> $GITHUB_OUTPUT
+          echo "country=$(jq -r '.country' ${{ env.ARTIFACT_NAME }})" >> $GITHUB_OUTPUT
+          echo "state=$(jq -r '.state' ${{ env.ARTIFACT_NAME }})" >> $GITHUB_OUTPUT
+          echo "locality=$(jq -r '.locality' ${{ env.ARTIFACT_NAME }})" >> $GITHUB_OUTPUT
+          echo "organization=$(jq -r '.organization' ${{ env.ARTIFACT_NAME }})" >> $GITHUB_OUTPUT
+          echo "common_name=$(jq -r '.common_name' ${{ env.ARTIFACT_NAME }})" >> $GITHUB_OUTPUT
 
   Terraform:
     runs-on: ubuntu-latest
@@ -101,7 +147,7 @@ jobs:
           terraform workspace select ${{ matrix.region }} || terraform workspace new ${{ matrix.region }}
 
           # tf plan destroy
-          terraform plan -var-file="region.${{ matrix.region }}.tfvars" -var "telegram_token_value=${{ env.TELEGRAM_TOKEN }}" -var "country=${{ needs.SetGlobals.outputs.country }}" -var "state=${{ needs.SetGlobals.outputs.state }}" -var "locality=${{ needs.SetGlobals.outputs.locality }}" -var "organization=${{ needs.SetGlobals.outputs.organization }}" -var "common_name=${{ needs.SetGlobals.outputs.common_name }}" -destroy -out region.${{ matrix.region }}.tfplan
+          terraform plan -var-file="region.${{ matrix.region }}.tfvars" -var "telegram_token_value=${{ env.TELEGRAM_TOKEN }}" -var "country=${{ needs.SetGlobals.outputs.country }}" -var "state=${{ needs.SetGlobals.outputs.state }}" -var "locality=${{ needs.SetGlobals.outputs.locality }}" -var "organization=${{ needs.SetGlobals.outputs.organization }}" -var "common_name=${{ needs.SetGlobals.outputs.common_name }}" -destroy -out region.${{ matrix.region }}.${{ inputs.environment }}.tfplan
 
           # tf apply
-          terraform apply -auto-approve region.${{ matrix.region }}.tfplan
+          terraform apply -auto-approve region.${{ matrix.region }}.${{ inputs.environment }}.tfplan
diff --git a/.github/workflows/polybot-deployment.yaml b/.github/workflows/polybot-deployment.yaml
--- a/.github/workflows/polybot-deployment.yaml
+++ b/.github/workflows/polybot-deployment.yaml
@@ -28,8 +28,49 @@ on:
           - 'dev'
 
 jobs:
+  GetRunId:
+    runs-on: ubuntu-latest
+    outputs:
+      run_id: ${{ steps.set_run_id.outputs.run_id }}
+    steps:
+      - name: Check and Install curl
+        run: |
+          if ! command -v curl &> /dev/null
+          then
+            echo "curl could not be found. Installing curl..."
+            sudo apt-get update
+            sudo apt-get install -y curl
+          else
+            echo "curl is already installed."
+          fi
+
+      - name: Check and Install jq
+        run: |
+          if ! command -v jq &> /dev/null
+          then
+            echo "jq could not be found. Installing jq..."
+            sudo apt-get update
+            sudo apt-get install -y jq
+          else
+            echo "jq is already installed."
+          fi
+
+      - name: Fetch the latest successful workflow run ID from the Infra Deployment
+        id: set_run_id
+        run: |
+          LATEST_SUCCESS=$(curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
+            -H "Accept: application/vnd.github.v3+json" \
+            "https://api.github.com/repos/talorlik/INTPolybotServiceAWS/actions/workflows/infra-provisioning-main.yaml/runs?status=success&per_page=1" \
+            | jq -r '.workflow_runs[0].id')
+
+          echo "run_id=$LATEST_SUCCESS" >> $GITHUB_OUTPUT
+
+          echo "The latest successful run ID is $LATEST_SUCCESS"
+
   SetGlobals:
     runs-on: ubuntu-latest
+    needs:
+      - GetRunId
     outputs:
       region_code: ${{ steps.set_region.outputs.region_code }}
       telegram_app_url: ${{ steps.set_values.outputs.telegram_app_url }}
@@ -62,25 +103,30 @@ jobs:
           echo "region_code=${SELECTED_REGION%%:*}" >> $GITHUB_OUTPUT
 
       - name: Download Output JSON file
-        uses: actions/download-artifact@v2
+        uses: actions/download-artifact@v4
         with:
           name: "${{ steps.set_region.outputs.region_code }}-${{ inputs.environment }}-tf-outputs.json"
+          github-token: ${{ secrets.GH_TOKEN }}
+          repository: talorlik/INTPolybotServiceAWS
+          run-id: ${{ needs.GetRunId.outputs.run_id }}
           path: ${{ github.workspace }}
 
       - name: Extract outputs from file and set as environment variables
         id: set_values
+        env:
+          ARTIFACT_NAME: "${{ steps.set_region.outputs.region_code }}-${{ inputs.environment }}-tf-outputs.json"
         run: |
-          echo "telegram_app_url=https://$(jq -r '.sub_domain_name' tf-outputs.json)" >> $GITHUB_OUTPUT
-          echo "telegram_secret=$(jq -r '.telegram_secret_name' tf-outputs.json)" >> $GITHUB_OUTPUT
-          echo "sub_domain_secret=$(jq -r '.sub_domain_secret_name' tf-outputs.json)" >> $GITHUB_OUTPUT
-          echo "sqs_queue_identify=$(jq -r '.identify_queue_name' tf-outputs.json)" >> $GITHUB_OUTPUT
-          echo "sqs_queue_results=$(jq -r '.results_queue_name' tf-outputs.json)" >> $GITHUB_OUTPUT
-          echo "bucket_name=$(jq -r '.s3_bucket_name' tf-outputs.json)" >> $GITHUB_OUTPUT
-          echo "bucket_prefix=$(jq -r '.s3_bucket_prefix' tf-outputs.json)" >> $GITHUB_OUTPUT
-          echo "table_name=$(jq -r '.table_name' tf-outputs.json)" >> $GITHUB_OUTPUT
-          echo "ecr_repository_url=$(jq -r '.ecr_repository_url' tf-outputs.json)" >> $GITHUB_OUTPUT
-          echo "image_prefix=$(jq -r '.polybot_image_prefix' tf-outputs.json)" >> $GITHUB_OUTPUT
-          echo "key_pair_name=$(jq -r '.key_pair_name' tf-outputs.json)" >> $GITHUB_OUTPUT
+          echo "telegram_app_url=https://$(jq -r '.sub_domain_name' ${{ env.ARTIFACT_NAME }})" >> $GITHUB_OUTPUT
+          echo "telegram_secret=$(jq -r '.telegram_secret_name' ${{ env.ARTIFACT_NAME }})" >> $GITHUB_OUTPUT
+          echo "sub_domain_secret=$(jq -r '.sub_domain_secret_name' ${{ env.ARTIFACT_NAME }})" >> $GITHUB_OUTPUT
+          echo "sqs_queue_identify=$(jq -r '.identify_queue_name' ${{ env.ARTIFACT_NAME }})" >> $GITHUB_OUTPUT
+          echo "sqs_queue_results=$(jq -r '.results_queue_name' ${{ env.ARTIFACT_NAME }})" >> $GITHUB_OUTPUT
+          echo "bucket_name=$(jq -r '.s3_bucket_name' ${{ env.ARTIFACT_NAME }})" >> $GITHUB_OUTPUT
+          echo "bucket_prefix=$(jq -r '.s3_bucket_prefix' ${{ env.ARTIFACT_NAME }})" >> $GITHUB_OUTPUT
+          echo "table_name=$(jq -r '.table_name' ${{ env.ARTIFACT_NAME }})" >> $GITHUB_OUTPUT
+          echo "ecr_repository_url=$(jq -r '.ecr_repository_url' ${{ env.ARTIFACT_NAME }})" >> $GITHUB_OUTPUT
+          echo "image_prefix=$(jq -r '.polybot_image_prefix' ${{ env.ARTIFACT_NAME }})" >> $GITHUB_OUTPUT
+          echo "key_pair_name=$(jq -r '.key_pair_name' ${{ env.ARTIFACT_NAME }})" >> $GITHUB_OUTPUT
 
   Build:
     runs-on: ubuntu-latest
@@ -117,6 +163,7 @@ jobs:
     name: Deploy Latest Poluybot Docker Container
     runs-on: ubuntu-latest
     needs:
+      - GetRunId
       - SetGlobals
       - Build
     env:
@@ -130,9 +177,12 @@ jobs:
           pip install ansible boto3
 
       - name: Download SSH Key
-        uses: actions/download-artifact@v2
+        uses: actions/download-artifact@v4
         with:
           name: "${{ env.ARTIFACT_PREFIX }}-${{ env.PEM_FILE_NAME }}"
+          github-token: ${{ secrets.GH_TOKEN }}
+          repository: talorlik/INTPolybotServiceAWS
+          run-id: ${{ needs.GetRunId.outputs.run_id }}
           path: ${{ env.LOCAL_PATH }}
 
       - name: Set permissions for SSH Key and Directory
